<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class Test {
    
    private $arr1;
    private $arr2;

    function contruct() {
        
    }

    function index() {
        $start_timestamp = microtime(true);
      $rs1 =   in_array("DAS_MAP_MOD", array("PMY_GRP_SEA",
        "PMY_EMP_SEA",
        "ADM_EQI_CAU",
        "ADM_EQI_MAC",
        "ADM_EMP_GRA",
        "ADM_EMP_EMP",
        "ADM_WAR_DEL",
        "ADM_WAR_ADD",
        "ADM_BRA_POR",
        "PMA_EMP_UPD",
        "ADM_CAU_EDT",
        "ADM_MUN_DEL",
        "ADM_MUN_EDT",
        "ADM_MPA_EDT",
        "ADM_MPA_ADD",
        "ADM_EGA_EDT",
        "ADM_EMP_DEL",
        "ADM_POR_DEL",
        "ADM_POR_EDT",
        "ADM_SPA_DET",
        "ADM_SPA_SMA",
        "ADM_MAI_POS",
        "ADM_EQI_IMG",
        "ADM_EQI_TEC",
        "ADM_EQI_EDT",
        "ADM_EQI_DEL",
        "ADM_BRA_ACT",
        "CMA_REP_XLS",
        "PMA_TIM_EDT",
        "PMA_LIM_GRO",
        "ADM_EGA_VIE",
        "ADM_WAR_EDT",
        "ADM_EGO_DEL",
        "ADM_EGO_EDT",
        "ADM_EGO_ADD",
        "ADM_EQI_MPA",
        "ADM_EMP_GRO",
        "ADM_BRA_WAR",
        "ADM_EQI_ADD",
        "ADM_SPA_ACT",
        "ADM_CAU_DEL",
        "ADM_CAU_ADD",
        "ADM_MPA_AEP",
        "ADM_MUN_ADD",
        "ADM_MPA_DEL",
        "ADM_EGA_DEL",
        "ADM_EGA_ADD",
        "ADM_POR_OEE",
        "ADM_EMP_EDT",
        "ADM_POR_ADD",
        "ADM_MAI_DIM",
        "ADM_MAI_UNI",
        "ADM_SPA_WAR",
        "ADM_SPA_UNI",
        "ADM_SPA_SPA",
        "DAS_SLS_CRE",
        "DAS_SLT_MOD",
        "ADM_POS_DEL",
        "ADM_POS_EDT",
        "ADM_POS_ADD",
        "ADM_EQI_DOC",
        "ADM_MAC_ACT",
        "ADM_MAC_DEL",
        "ADM_PMA_DEL",
        "CRE_OEE",
        "ADM_MAC_ADD",
        "ADM_MAC_CPY",
        "ADM_MAC_EDT",
        "ADM_MAC_VIE",
        "ADM_PMA_ADD",
        "ADM_PMA_CPY",
        "ADM_PMA_EDT",
        "ADM_PMA_VIE",
        "ADM_STA_MOD",
        "ADM_TAS_CRE",
        "SEA_LIB_CPY",
        "PMB_TIC_DEL",
        "ADM_ASS_ACT",
        "ADM_LOG_ACT",
        "ADM_MAI_ACT",
        "ADM_WFL_ACT",
        "ADM_SUP_ACT",
        "ADM_CAT_ACT",
        "ADM_MAN_ADD",
        "ADM_GRP_ADD",
        "ADM_EMP_ADD",
        "ADM_EMP_ACT",
        "ADM_COS_ADD",
        "ADM_INV_ADD",
        "ADM_COM_ACT",
        "PMB_LOG_RES",
        "PMB_TLI_USE",
        "PMB_TLI_PRI",
        "PMB_TIC_VIE",
        "PMB_TIC_CRE",
        "PMB_SPA_CRE",
        "PMB_REP_XLS",
        "PMB_NOT_VIE",
        "PMB_NOT_MOD",
        "PMB_NOT_CRE",
        "PMB_GRP_SEA",
        "SPA_OIL_ORD",
        "SPA_OIL_EDT",
        "SPA_OIL_VIE",
        "DAS_BRA_SEL",
        "SPA_EMP_SEA",
        "SPA_ORD_VIE",
        "SPA_ORD_APR",
        "SPA_ORD_SEN",
        "SPA_MAT_EDT",
        "SPA_MAT_DEL",
        "SPA_MAT_VIE",
        "SPA_ORD_CON",
        "SPA_ORD_EDT",
        "TAB_CMA_VIE",
        "TAB_DAS_VIE",
        "PMA_REP_XLS",
        "TYP_LST_VIE",
        "CON_LST_VIE",
        "DAS_STA_VIE",
        "TAB_TRE_VIE",
        "CMA_ORD_MOD",
        "CAL_HOL_CRE",
        "CAL_PER_CRE",
        "CAL_TAS_CRE",
        "ATT_PMA_DOW",
        "ATT_PMA_DEL",
        "ATT_PMA_UPL",
        "ATT_PMA_VIE",
        "ATT_CMA_DOW",
        "ATT_CMA_DEL",
        "ATT_CMA_UPL",
        "CMA_SPA_CRE",
        "CMA_NOT_MOD",
        "ATT_CMA_VIE",
        "ATT_MAC_DOW",
        "ATT_MAC_DEL",
        "ATT_MAC_UPL",
        "ATT_MAC_VIE",
        "PMA_SPA_CRE",
        "PMA_NOT_MOD",
        "PMA_NOT_DEL",
        "PMA_NOT_CRE",
        "PMA_NOT_VIE",
        "PMA_TIC_DEL",
        "PMA_TIC_CRE",
        "PMA_TIC_VIE",
        "CMA_NOT_DEL",
        "CMA_TIC_CRE",
        "CMA_TIC_VIE",
        "SPA_INV_VIE",
        "SPA_PRO_VIE",
        "PMA_TLI_USE",
        "PMA_TLI_PRI",
        "DAS_CHA_VIE",
        "TAB_ADM_VIE",
        "TAB_DOC_VIE",
        "CMA_NOT_CRE",
        "CMA_NOT_VIE",
        "CMA_TIC_DEL",
        "CMA_TIC_MOD",
        "SPA_MAT_CRE",
        "PMA_LOG_RES",
        "PMA_LOG_MOD",
        "PMA_LOG_VIE",
        "CMA_TLI_PRI",
        "CMA_TLI_USE",
        "CAL_TAS_MOD",
        "TAB_CAL_VIE",
        "TAB_SPA_VIE",
        "TAB_PMA_VIE",
        "CAL_PER_MOD",
        "CAL_HOL_MOD",
        "CAL_EMP_SEA",
        "SPA_ORD_CRE",
        "SPA_PRO_MOD",
        "PMA_EMP_SEA",
        "CMA_EMP_SEA",
        "DAS_CON_DEL",
        "DAS_CON_CRE",
        "DAS_CON_MOD",
        "DAS_CON_VIE",
        "DAS_MAP_MOD",
        "DAS_MAP_VIE",
        "DAS_GRI_MOD",
        "DAS_GRI_VIE",
        "PER_NOT_DEL",
        "PER_NOT_MOD",
        "PER_NOT_CRE",
        "TAB_REP_VIE",
        "TAB_FIN_VIE",
        "ADM_DEC_VIE",
        "PMB_LIM_VIE",
        "PMA_LIM_VIE",
        "ADM_PMA_EMP",
        "ADM_POS_AAG",
        "SEA_LIB_VIE",
        "SEA_SEA_VIE",
        "IMP_PMA_CPY",
        "IMP_PMA_EDT",
        "IMP_PMA_DEL",
        "IMP_SEA_VIE",
        "IMP_NEW_REC",
        "IMP_FIL_BTU",
        "IMP_FIL_PMU",
        "IMP_FIL_VIE",
        "TAB_PMB_VIE",
        "PMB_PRD_NEW",
        "SPA_BUY_CRE",
        "FAC_ORG_VIE",
        "SPA_ORD_DEL",
        "DAS_TSX_MOD",
        "DAS_STO_CRE",
        "DAS_PLA_CRE",
        "DAS_SLP_CRE",
        "DAS_OEE_VIE",
        "FAC_GRP_MAC",
        "TAB_JOB_VIE",
        "PMA_GRP_SEM",
        "CMA_GRP_SEA",
        "PMA_GRP_SEA",
        "ADM_MEM_DEC",
        "ADM_MEM_ADD",
        "ADM_MEM_VIE",
        "ADM_EXC_EXP",
        "ADM_EXC_IMP",
        "ADM_GRR_ADD",
        "ADM_SYS_ACT"));
        $end_timestamp = microtime(true);
        $duration = $end_timestamp - $start_timestamp;
        echo "Execution took " . $duration . " milliseconds. ". $rs1;
        
        $start_timestamp1 = microtime(true);
    $rs2 =     array("PMY_GRP_SEA" => true,
        "PMY_EMP_SEA" => true,
        "ADM_EQI_CAU" => true,
        "ADM_EQI_MAC" => true,
        "ADM_EMP_GRA" => true,
        "ADM_EMP_EMP" => true,
        "ADM_WAR_DEL" => true,
        "ADM_WAR_ADD" => true,
        "ADM_BRA_POR" => true,
        "PMA_EMP_UPD" => true,
        "ADM_CAU_EDT" => true,
        "ADM_MUN_DEL" => true,
        "ADM_MUN_EDT" => true,
        "ADM_MPA_EDT" => true,
        "ADM_MPA_ADD" => true,
        "ADM_EGA_EDT" => true,
        "ADM_EMP_DEL" => true,
        "ADM_POR_DEL" => true,
        "ADM_POR_EDT" => true,
        "ADM_SPA_DET" => true,
        "ADM_SPA_SMA" => true,
        "ADM_MAI_POS" => true,
        "ADM_EQI_IMG" => true,
        "ADM_EQI_TEC" => true,
        "ADM_EQI_EDT" => true,
        "ADM_EQI_DEL" => true,
        "ADM_BRA_ACT" => true,
        "CMA_REP_XLS" => true,
        "PMA_TIM_EDT" => true,
        "PMA_LIM_GRO" => true,
        "ADM_EGA_VIE" => true,
        "ADM_WAR_EDT" => true,
        "ADM_EGO_DEL" => true,
        "ADM_EGO_EDT" => true,
        "ADM_EGO_ADD" => true,
        "ADM_EQI_MPA" => true,
        "ADM_EMP_GRO" => true,
        "ADM_BRA_WAR" => true,
        "ADM_EQI_ADD" => true,
        "ADM_SPA_ACT" => true,
        "ADM_CAU_DEL" => true,
        "ADM_CAU_ADD" => true,
        "ADM_MPA_AEP" => true,
        "ADM_MUN_ADD" => true,
        "ADM_MPA_DEL" => true,
        "ADM_EGA_DEL" => true,
        "ADM_EGA_ADD" => true,
        "ADM_POR_OEE" => true,
        "ADM_EMP_EDT" => true,
        "ADM_POR_ADD" => true,
        "ADM_MAI_DIM" => true,
        "ADM_MAI_UNI" => true,
        "ADM_SPA_WAR" => true,
        "ADM_SPA_UNI" => true,
        "ADM_SPA_SPA" => true,
        "DAS_SLS_CRE" => true,
        "DAS_SLT_MOD" => true,
        "ADM_POS_DEL" => true,
        "ADM_POS_EDT" => true,
        "ADM_POS_ADD" => true,
        "ADM_EQI_DOC" => true,
        "ADM_MAC_ACT" => true,
        "ADM_MAC_DEL" => true,
        "ADM_PMA_DEL" => true,
        "CRE_OEE" => true,
        "ADM_MAC_ADD" => true,
        "ADM_MAC_CPY" => true,
        "ADM_MAC_EDT" => true,
        "ADM_MAC_VIE" => true,
        "ADM_PMA_ADD" => true,
        "ADM_PMA_CPY" => true,
        "ADM_PMA_EDT" => true,
        "ADM_PMA_VIE" => true,
        "ADM_STA_MOD" => true,
        "ADM_TAS_CRE" => true,
        "SEA_LIB_CPY" => true,
        "PMB_TIC_DEL" => true,
        "ADM_ASS_ACT" => true,
        "ADM_LOG_ACT" => true,
        "ADM_MAI_ACT" => true,
        "ADM_WFL_ACT" => true,
        "ADM_SUP_ACT" => true,
        "ADM_CAT_ACT" => true,
        "ADM_MAN_ADD" => true,
        "ADM_GRP_ADD" => true,
        "ADM_EMP_ADD" => true,
        "ADM_EMP_ACT" => true,
        "ADM_COS_ADD" => true,
        "ADM_INV_ADD" => true,
        "ADM_COM_ACT" => true,
        "PMB_LOG_RES" => true,
        "PMB_TLI_USE" => true,
        "PMB_TLI_PRI" => true,
        "PMB_TIC_VIE" => true,
        "PMB_TIC_CRE" => true,
        "PMB_SPA_CRE" => true,
        "PMB_REP_XLS" => true,
        "PMB_NOT_VIE" => true,
        "PMB_NOT_MOD" => true,
        "PMB_NOT_CRE" => true,
        "PMB_GRP_SEA" => true,
        "SPA_OIL_ORD" => true,
        "SPA_OIL_EDT" => true,
        "SPA_OIL_VIE" => true,
        "DAS_BRA_SEL" => true,
        "SPA_EMP_SEA" => true,
        "SPA_ORD_VIE" => true,
        "SPA_ORD_APR" => true,
        "SPA_ORD_SEN" => true,
        "SPA_MAT_EDT" => true,
        "SPA_MAT_DEL" => true,
        "SPA_MAT_VIE" => true,
        "SPA_ORD_CON" => true,
        "SPA_ORD_EDT" => true,
        "TAB_CMA_VIE" => true,
        "TAB_DAS_VIE" => true,
        "PMA_REP_XLS" => true,
        "TYP_LST_VIE" => true,
        "CON_LST_VIE" => true,
        "DAS_STA_VIE" => true,
        "TAB_TRE_VIE" => true,
        "CMA_ORD_MOD" => true,
        "CAL_HOL_CRE" => true,
        "CAL_PER_CRE" => true,
        "CAL_TAS_CRE" => true,
        "ATT_PMA_DOW" => true,
        "ATT_PMA_DEL" => true,
        "ATT_PMA_UPL" => true,
        "ATT_PMA_VIE" => true,
        "ATT_CMA_DOW" => true,
        "ATT_CMA_DEL" => true,
        "ATT_CMA_UPL" => true,
        "CMA_SPA_CRE" => true,
        "CMA_NOT_MOD" => true,
        "ATT_CMA_VIE" => true,
        "ATT_MAC_DOW" => true,
        "ATT_MAC_DEL" => true,
        "ATT_MAC_UPL" => true,
        "ATT_MAC_VIE" => true,
        "PMA_SPA_CRE" => true,
        "PMA_NOT_MOD" => true,
        "PMA_NOT_DEL" => true,
        "PMA_NOT_CRE" => true,
        "PMA_NOT_VIE" => true,
        "PMA_TIC_DEL" => true,
        "PMA_TIC_CRE" => true,
        "PMA_TIC_VIE" => true,
        "CMA_NOT_DEL" => true,
        "CMA_TIC_CRE" => true,
        "CMA_TIC_VIE" => true,
        "SPA_INV_VIE" => true,
        "SPA_PRO_VIE" => true,
        "PMA_TLI_USE" => true,
        "PMA_TLI_PRI" => true,
        "DAS_CHA_VIE" => true,
        "TAB_ADM_VIE" => true,
        "TAB_DOC_VIE" => true,
        "CMA_NOT_CRE" => true,
        "CMA_NOT_VIE" => true,
        "CMA_TIC_DEL" => true,
        "CMA_TIC_MOD" => true,
        "SPA_MAT_CRE" => true,
        "PMA_LOG_RES" => true,
        "PMA_LOG_MOD" => true,
        "PMA_LOG_VIE" => true,
        "CMA_TLI_PRI" => true,
        "CMA_TLI_USE" => true,
        "CAL_TAS_MOD" => true,
        "TAB_CAL_VIE" => true,
        "TAB_SPA_VIE" => true,
        "TAB_PMA_VIE" => true,
        "CAL_PER_MOD" => true,
        "CAL_HOL_MOD" => true,
        "CAL_EMP_SEA" => true,
        "SPA_ORD_CRE" => true,
        "SPA_PRO_MOD" => true,
        "PMA_EMP_SEA" => true,
        "CMA_EMP_SEA" => true,
        "DAS_CON_DEL" => true,
        "DAS_CON_CRE" => true,
        "DAS_CON_MOD" => true,
        "DAS_CON_VIE" => true,
        "DAS_MAP_MOD" => true,
        "DAS_MAP_VIE" => true,
        "DAS_GRI_MOD" => true,
        "DAS_GRI_VIE" => true,
        "PER_NOT_DEL" => true,
        "PER_NOT_MOD" => true,
        "PER_NOT_CRE" => true,
        "TAB_REP_VIE" => true,
        "TAB_FIN_VIE" => true,
        "ADM_DEC_VIE" => true,
        "PMB_LIM_VIE" => true,
        "PMA_LIM_VIE" => true,
        "ADM_PMA_EMP" => true,
        "ADM_POS_AAG" => true,
        "SEA_LIB_VIE" => true,
        "SEA_SEA_VIE" => true,
        "IMP_PMA_CPY" => true,
        "IMP_PMA_EDT" => true,
        "IMP_PMA_DEL" => true,
        "IMP_SEA_VIE" => true,
        "IMP_NEW_REC" => true,
        "IMP_FIL_BTU" => true,
        "IMP_FIL_PMU" => true,
        "IMP_FIL_VIE" => true,
        "TAB_PMB_VIE" => true,
        "PMB_PRD_NEW" => true,
        "SPA_BUY_CRE" => true,
        "FAC_ORG_VIE" => true,
        "SPA_ORD_DEL" => true,
        "DAS_TSX_MOD" => true,
        "DAS_STO_CRE" => true,
        "DAS_PLA_CRE" => true,
        "DAS_SLP_CRE" => true,
        "DAS_OEE_VIE" => true,
        "FAC_GRP_MAC" => true,
        "TAB_JOB_VIE" => true,
        "PMA_GRP_SEM" => true,
        "CMA_GRP_SEA" => true,
        "PMA_GRP_SEA" => true,
        "ADM_MEM_DEC" => true,
        "ADM_MEM_ADD" => true,
        "ADM_MEM_VIE" => true,
        "ADM_EXC_EXP" => true,
        "ADM_EXC_IMP" => true,
        "ADM_GRR_ADD" => true,
        "ADM_SYS_ACT" => true)['DAS_MAP_MOD'];
        $end_timestamp1 = microtime(true);
        $duration = $end_timestamp1 - $start_timestamp1;
        echo "<br>Execution took " . $duration . " milliseconds.". $rs2;
    }

}
